### ISSUE TITLE
Memory issues? Strange behaviour.

### ISSUE THREAD

**Issue by dietzc** [StephanPreibisch/FourierConvolutionCUDALib#11]
Hi @psteinb & @StephanPreibisch,

I'm using these CUDA implementations now for a while (thank you!), but I figured that there seems to be something really strange going on concerning the memory footprint of the implementation.

I'm using a Titan Black X with 12GB Memory (single memory, not two graphic cards or stuff) and compiled your code for CUDA 7. I see the same behaviour on linux and windows.

I figured, that I can easily convolve a float image of size 400^3 (which is length=64000000 and ~244MB) with a kernel of size (31x31x91) in-place.

However, an image of size 406_400_400  and same kernel size (31x31x91) already fails. By fails I mean, that the array I passed over to CUDA to perform the in-place convolution nearly only contains zeros after convolution. Some values are very close to zero.

I know that the memory footprint FFT is high, however, not over 24 times as high as my input image size?

Any ideas??

Thanks!
Christian

**Comment by StephanPreibisch** [comment]
It is a little bit unforeseeable how much RAM the FFT will actually take (CUDA FFT documentation). Ideally use power-of-two values or at least sums of powers-of-two to avoid these issues. So if the image size is 406, use 512 or maybe 448 (256+128+64), it will most likely use way less RAM.

**Comment by dietzc** [comment]
But 24 times the RAM of the input? This is really surprising.

**Comment by StephanPreibisch** [comment]
Try 512 instead, I am sure it will just work. My 4GB card crashed on 357x415x214 (or so) but computed 1024x1024x512. It is somehow related to the way it is implemented, which is not so easy using GPU hardware apparently.

**Comment by psteinb** [comment]
I'll add a test on it once I find the time to and post my findings here.

**Comment by dietzc** [comment]
Thanks for the hints. My GPU doesn't crash. Just my output contains tons of zeros and some values close to zero.

Some findings which are even more confusing:
- 512x512x512 doesn't work!
- 768x768x256 works
- 768x768x768 works
- 512x512x768 works
- 512x512x640 works
- 640x640x640 works
- 528x528x528 works
- 611x623x600 doesn't work

and finally:
- 1024x1024x1024 doesn't work (no GPU crash)

?!!

**Comment by dietzc** [comment]
I found the following at http://docs.nvidia.com/cuda/cufft/index.html#axzz3zUNEcPXh:

> Transform sizes up to 512 million elements in single precision and up to half that in double precision in any dimension, limited by the type of transform chosen and the available GPU memory

512x512x512 should work anyway

**Comment by psteinb** [comment]
Could you please specify the kernel you used to convolve the images with 
(shape is most important, content a bonsu)? I deem you filled the test 
3D volumes with arbitrary content?

**Comment by dietzc** [comment]
kernel size: (31x31x91). content is not arbitrary, it's a sample of my SPIM image. However, it should work with arbitrary content, right? can you convolve a 512^3 img?

**Comment by dietzc** [comment]
>  http://docs.nvidia.com/cuda/cufft/index.html#axzz3zUNEcPXh

it' also mentoined that dimensions sizes which can be factored into distinct primes in the form of  2^a_3^b_5^c*7^d are more efficient and depending on the input dimension on or the other algorithm is being used. what I did is the following: I created all 2^i, 3^i, 5^i and 7^i where 0 < i < K with (K = 10 in my case) and all multiplications of theses numbers. I added all numbers < 1025 to the list. If I calculate a bounding box now for some sample, I use the next bigger number of the list compared to the dimension of the bounding-box for the new bounding-box dimension and I don't have these problems anymore. However, it's still strange that 512^3 doesn't work. 

PS: potentially there is a more elegant way to find the next best suitable number. however, like this it works.

**Comment by psteinb** [comment]
@dietzc 
did you apply the cufft patch to your cuda 7?

**Comment by dietzc** [comment]
running Cuda 7.5.

**Comment by psteinb** [comment]
cuda 7.5 sounds good to me.

the kernel of shape 31x31x91, which dimension does 91 correspond to: x or z?

I am preparing some test cases that I'll publish to a dedicated branch. 
I'll keep you posted.

**Comment by dietzc** [comment]
it's X,Y,Z so Z=91. and: thanks!

**Comment by psteinb** [comment]
I created some test cases and could reproduce the problem for 512^3 and even 128^3. I am looking into this now. the code is at 
https://github.com/StephanPreibisch/FourierConvolutionCUDALib/tree/ticket11_memory_issues
more precisely:
https://github.com/StephanPreibisch/FourierConvolutionCUDALib/blob/ticket11_memory_issues/tests/test_gpu_memory_reach.cpp

**Comment by dietzc** [comment]
also the "non-inplace" (which is supposed to be faster than inplace according to the cufft doc) doesn't work for me anymore. and: thanks! +1 beer ;-)

**Comment by psteinb** [comment]
yeah, be careful about that though. the performance improvement for 
out-of-place versus inplace have always been /very minimal/ for me in 
the past. How much did you gain in the past and on what GPU?

**Comment by dietzc** [comment]
couldn't try it, yet as it's not working for me. But I can let you know.

**Comment by psteinb** [comment]
apparently, cufft changed the data layout that it's API accepts in CUDA 7. this library was written for the "old" cufft native format (declared deprecated by now). CUDA7.x supports FFTW compatible only AFAIK. I am looking into it, so give me some time.

**Comment by dietzc** [comment]
:+1:

**Comment by psteinb** [comment]
alright, some sentinels were missing that should be inplace to catch the error values of cufft. that is why your jobs ran through, but didn't produce any viable results! I fixed that (besides other things) and merged it into master. I also setup a small test suite to check if your GPU can convolve 16^3, 256^3,512^3 shaped signals. Once you build the library including the tests (remember boost must be installed for this), there should be an executable called `test_gpu_memory_reach`. Call it to see what your GPU supports (the app takes the "strongest" GPU found in the system). 

Once I find some time again, I do recall that there is a function to test how much memory cufft assumes to need for proper operatiion. We could use that to return an error code or something and tell the java client that something is wrong or to better not use the GPU for a given 3D volume.

In any case, I also stumbled upon a numerical defiency that cufft appears to have (which I already reported to nvidia):

```
$ ./tests/test_how_cufft_works --log_level=message
inplace    shape(x,y,z)=19, 17, 13      l2norm = 4510.09 #yikes!
inplace    shape(x,y,z)=16, 16, 16      l2norm = 5.33185e-07
inplace    shape(x,y,z)=27, 27, 27      l2norm = 4.26473e-06
inplace    shape(x,y,z)=25, 25, 25      l2norm = 8.05152e-06
inplace    shape(x,y,z)=14, 14, 14      l2norm = 3.12369e-06
inplace    shape(x,y,z)=128, 128, 128   l2norm = 5.01017e-05
outofplace shape(x,y,z)=19, 17, 13      l2norm = 0.00314017 #yikes!
outofplace shape(x,y,z)=16, 16, 16      l2norm = 5.33185e-07
outofplace shape(x,y,z)=27, 27, 27      l2norm = 4.26473e-06
outofplace shape(x,y,z)=25, 25, 25      l2norm = 8.05152e-06
outofplace shape(x,y,z)=14, 14, 14      l2norm = 3.12369e-06
outofplace shape(x,y,z)=128, 128, 128   l2norm = 5.01017e-05
```

For the above, I basically created a 3D volume with arbitrary input and performed ifft(fft(volume)). I then compared the result with the original. fftw does not show this behavior! I'll post any news from nvidia to this issue before closing it. 

At last, `convolution3DfftCUDAInPlace` is usable again with commit 70e9a0dcf49d63f62f4b6dab2af8792b2b1a797f!

**Comment by dietzc** [comment]
thanks for the investigations and fixes. I immediately try it on Friday. What I don't understand: You are saying some sizes of images are not supported by certain GPUs? Any way to recover besides finding multiples of `x^k * y^i * z^j`?

**Comment by psteinb** [comment]
hi @dietzc, what I am saying is that I suspect that libcufft (not the GPUs!) does only support pixel volumes where any dimension extends to `2^a * 3^b * 5^c * 7^d` with [a,b,c,d] being an integer number. If you padd to these numbers cufft works, if not you'll get garbage. And the funny thing, cufft doesn't even tell you.

**Comment by dietzc** [comment]
yep. this is how I resolved my problem.  Thanks for confirming this! What I still don't understand is why `512x512x512` isn't working. Bug in ...?

**Comment by psteinb** [comment]
What error code do you get from cufftPlan3D? Or what is the output of test_gpu_memory_reach on that box?

**Comment by dietzc** [comment]
Ok. I see. I will definitively try it out tomorrow and let you know. No I'm in sync with your efforts again :+1: thanks!

**Comment by dietzc** [comment]
following error when running `test_gpu_memory_reach`: 

```
/home/admin/Desktop/git-repos/FourierConvolutionCUDALib/tests/test_gpu_memory_reach.cpp(192): fatal error in "identity_convolve_512": failed due to CUFFT_ALLOC_FAILED in /home/admin/Desktop/git-repos/FourierConvolutionCUDALib/src/convolution3Dfft.cu at line 501

 do not use convolution3DfftCUDAInPlace on this GPU with shapes larger than (x,y,z) = 512x512x512

*** 1 failure detected in test suite "GPU_MEMORY_REACH"
```

however I have 12GB of RAM (GeForce Titan X) I also successfully convolved images of size 768x768x768

**Comment by dietzc** [comment]
second failing test `./test_how_cufft_works`:

```
/home/admin/Desktop/git-repos/FourierConvolutionCUDALib/tests/test_how_cufft_works.cu(210): fatal error in "of_prime_shape": l2norm = nan not smaller than 0.1

*** 1 failure detected in test suite "HOW_CUFFT_WORKS"
```

**Comment by psteinb** [comment]
I believe the memory problem has to be considered independent of the numerical issue reported. I still hope that the latter is due to a bug in my code. I'll open a dedicated ticket on this tomorrow. I should have done this in the first place.

The issue with the Titan X is weird. Can you share your Nvidia driver version, OS and potentially the host compiler used?

**Comment by dietzc** [comment]
> I believe the memory problem has to be considered independent of the numerical issue reported. I still hope that the latter is due to a bug in my code. I'll open a dedicated ticket on this tomorrow. I should have done this in the first place.

Great, thanks. +1 beer for you next time I'm in Dresden :+1: 

> The issue with the Titan X is weird. Can you share your Nvidia driver version, OS and potentially the host compiler used?

Sure I can, however the problem also occurs another windows machine (same GPU). Anyway, here are my settings:
- `nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2015 NVIDIA Corporation
  Built on Mon_Feb_16_22:59:02_CST_2015
  Cuda compilation tools, release 7.0, V7.0.27`. 
- `+------------------------------------------------------+                       
  | NVIDIA-SMI 352.79     Driver Version: 352.79         |                       
  |-------------------------------+----------------------+----------------------+
  | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
  |===============================+======================+======================|
  |   0  GeForce GTX TIT...  Off  | 0000:03:00.0      On |                  N/A |
  | 22%   29C    P8    23W / 250W |    181MiB / 12287MiB |      0%      Default |
  +-------------------------------+----------------------+----------------------+`
- Ubuntu 15.10, GNOME3

Should I switch to Cuda 7.5?

**Comment by psteinb** [comment]
I don't think this issue is cuda version related. I tried my code and the nvidia SDK code (7_CUDALibraries/test_simpleCUFFT updated to 512x512x512) on a GTX Titan Black (6GB) and a K80 (2x12GB) and in all cases the code crashes. I also tried 768^3, with the same result. Let me see, if I can ask cufft how much memory it might need.

**Comment by psteinb** [comment]
well, [cufftEstimate3d](http://docs.nvidia.com/cuda/cufft/#function-cufftestimate3d) throws an error when confronted with 512x512x512 and returns a CUFFT_ALLOC_FAILED status. Feel free to submit a bug report to nvidia, or I'll do it early next week (just let me know). 

btw, can you try again to convolve a 768x768x768 stack with the library, I suspect it won't work now. But it's better to check.

**Comment by dietzc** [comment]
> I don't think this issue is cuda version related. I tried my code and the nvidia SDK code (7_CUDALibraries/test_simpleCUFFT updated to 512x512x512) on a GTX Titan Black (6GB) and a K80 (2x12GB) and in all cases the code crashes. I also tried 768^3, with the same result. Let me see, if I can ask cufft how much memory it might need.

768^3 worked for me. also several other settings > 512^3. Very strange, ...
